language: node_js

node_js:
- '12'

script: npm run test:ci

notifications:
  email: false

cache:
  directories:
  - node_modules

after_success:
- npm run codecov

addons:
  chrome: stable

dist: trusty

sudo: required
