import {
  addDays,
  addHours,
  addMinutes,
  addSeconds,
  differenceInDays,
  differenceInMinutes,
  differenceInSeconds,
  endOfDay,
  endOfMonth,
  endOfWeek,
  getDay,
  getMonth,
  isSameDay,
  isSameMonth,
  isSameSecond,
  max,
  setHours,
  setMinutes,
  startOfDay,
  startOfMinute,
  startOfMonth,
  startOfWeek,
  getHours,
  getMinutes
} from 'date-fns';
import { DateAdapter } from '../date-adapter';

export function adapterFactory(): DateAdapter {
  return {
    addDays,
    addHours,
    addMinutes,
    addSeconds,
    differenceInDays,
    differenceInMinutes,
    differenceInSeconds,
    endOfDay,
    endOfMonth,
    endOfWeek,
    getDay,
    getMonth,
    isSameDay,
    isSameMonth,
    isSameSecond,
    max: (...dates) => max(dates),
    setHours,
    setMinutes,
    startOfDay,
    startOfMinute,
    startOfMonth,
    startOfWeek,
    getHours,
    getMinutes
  };
}
